#!/usr/bin/env python3
"""Regenerates src/data/pdfFont.generated.ts, the embedded font for PDF export.

jsPDF's built-in fonts don't cover Hungarian diacritics (ő/ű), so the PDF export feature
embeds a real font instead. This script takes Inter's variable font, instances it down to
a single static weight, and subsets it to Latin + Latin Extended-A (drops everything else
Inter ships — Cyrillic, Greek, etc.) to keep the embedded/base64 payload small.

Requires:
    npm install typeface-inter --no-save
    pip install fonttools

Re-run only if the embedded PDF font needs to change. The output is committed like
curriculum.json — don't hand-edit it.
"""
import base64
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_TTF = (
    ROOT / "node_modules" / "typeface-inter" / "Inter Variable" / "Single axis" / "Inter-roman.ttf"
)
OUT_TS = ROOT / "src" / "data" / "pdfFont.generated.ts"
TMP_STATIC = ROOT / "scripts" / "_inter-400.ttf"
TMP_SUBSET = ROOT / "scripts" / "_inter-400-subset.ttf"


def run(*args: str) -> None:
    subprocess.run(args, check=True)


def main() -> None:
    if not SRC_TTF.exists():
        sys.exit(f"Missing {SRC_TTF} -- run `npm install typeface-inter --no-save` first.")

    try:
        run(
            sys.executable,
            "-m",
            "fontTools.varLib.instancer",
            str(SRC_TTF),
            "wght=400",
            "-o",
            str(TMP_STATIC),
        )
        run(
            sys.executable,
            "-m",
            "fontTools.subset",
            str(TMP_STATIC),
            f"--output-file={TMP_SUBSET}",
            "--unicodes=U+0000-00FF,U+0100-017F,U+2010-2015,U+2018-201E",
            "--layout-features=*",
            "--glyph-names",
            "--symbol-cmap",
            "--legacy-cmap",
            "--notdef-glyph",
            "--notdef-outline",
            "--recommended-glyphs",
            "--name-IDs=*",
            "--name-legacy",
            "--name-languages=*",
        )
        b64 = base64.b64encode(TMP_SUBSET.read_bytes()).decode("ascii")
    finally:
        TMP_STATIC.unlink(missing_ok=True)
        TMP_SUBSET.unlink(missing_ok=True)

    OUT_TS.write_text(
        "/** Generated by scripts/generate_pdf_font.py — do not hand-edit. */\n"
        "/** Inter Regular, instanced to weight 400 and subset to Latin + Latin Extended-A, "
        "base64-encoded TTF. */\n"
        f'export const PDF_FONT_BASE64 = "{b64}";\n'
    )
    kb = len(b64) * 3 // 4 // 1024
    print(f"Wrote {OUT_TS} ({len(b64)} base64 chars, ~{kb} KB decoded)")


if __name__ == "__main__":
    main()
